@echo off
echo started at %date% %time% > started.txt
echo Starting slow task...
echo Waiting 3 minutes...
ping 127.0.0.1 -n 181 >nul
echo Writing completion file...
echo done at %date% %time% > task_complete.txt
echo Task complete!
