"""Routine A: one-off, produces a reviewable draft with an explicit review state.

This script MUST NOT trigger Routine B or set any approval. It only creates a
draft on a branch plus a review artifact whose initial state is 'pending'.
"""

import json
import os
import time

from loopcore import load_config, load_state, save_state, check_limits, git, BASE_DIR


def main():
    cfg = load_config()
    state = load_state()

    ok, reason = check_limits(state)
    if not ok:
        print("ROUTINE A STOPPED: " + reason)
        return

    # Hard limit bookkeeping.
    state["iterations"] += 1
    if state.get("deadline") is None:
        state["deadline"] = time.time() + cfg["limits"]["max_minutes"] * 60

    draft_no = state["iterations"]
    branch = "a/draft-%d" % draft_no
    draft_path = os.path.join(BASE_DIR, "drafts", "draft-%d.md" % draft_no)
    review_path = os.path.join(BASE_DIR, "drafts", "review-%d.json" % draft_no)

    # Create an isolated branch for the draft (no push to any remote).
    git(["checkout", "-b", branch])
    git(["reset", "--hard", "HEAD"])  # start clean from current HEAD

    summary = (
        "# Routine A draft #%d\n\n"
        "Generated by Routine A (one-off). This is a reviewable artifact.\n"
        "Topic: loop-engineering exercise for project-11.\n"
        "Review state: PENDING (set by Routine A; not approved).\n"
    ) % draft_no
    with open(draft_path, "w") as f:
        f.write(summary)

    review = {
        "draft_no": draft_no,
        "draft_path": os.path.relpath(draft_path, BASE_DIR),
        "branch": branch,
        "review_state": "pending",
        "approved_by": None,
        "approved_via": None,
        "approved_at": None,
        "produced_at": time.time(),
    }
    with open(review_path, "w") as f:
        json.dump(review, f, indent=2)

    git(["add", os.path.relpath(draft_path, BASE_DIR),
         os.path.relpath(review_path, BASE_DIR)])
    git(["commit", "-m", "Routine A draft #%d (pending review)" % draft_no])

    # Leave HEAD on the draft branch: the branch IS the reviewable artifact.
    # The human reviews here; Routine B will re-checkout it to apply the
    # follow-up, then return to main. We never push.

    state["a"] = {
        "status": "produced",
        "draft": os.path.relpath(draft_path, BASE_DIR),
        "review_state": "pending",
        "branch": branch,
    }
    save_state(state)

    print("ROUTINE A produced draft #%d on branch '%s'." % (draft_no, branch))
    print("Review required. review_state=pending. B must NOT run yet.")
    print("Draft: %s" % draft_path)


if __name__ == "__main__":
    main()
